AWSTemplateFormatVersion: '2010-09-09'
Description: ElastiCache Setup

Parameters:

  ElastiCacheSecurityGroupId:
    Type: String
    Description: Security Group ID for the ElastiCache

  EC2PrivateSubnetAZ1Id:
    Type: String
    Description: Private Subnet ID for EC2 web server instances in AZ1

  EC2PrivateSubnetAZ2Id:
    Type: String
    Description: Private Subnet ID for EC2 web server instances in AZ2

  ECommerceVPC:
    Type: String
    Description: VPC ID for the network


Resources:

 

  # Subnet group for ElastiCache (Private Subnets)
  ElastiCacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: "ElastiCache Subnet Group in private subnets"
      SubnetIds:
        - !Ref EC2PrivateSubnetAZ1Id  
        - !Ref EC2PrivateSubnetAZ2Id


  # ElastiCache Redis Cluster in private subnets
  MyElastiCacheCluster:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties: 
      ReplicationGroupDescription: "Redis replication group for session management"
      CacheNodeType: "cache.t3.micro"  # Choose appropriate instance type
      Engine: "redis"
      NumCacheClusters: 2  # Multi-AZ deployment
      AutomaticFailoverEnabled: true  # Enables multi-AZ with automatic failover
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      SecurityGroupIds:
        - !Ref ElastiCacheSecurityGroupId
      MultiAZEnabled: true
